if(EMSCRIPTEN)
    set(AURA_ENABLE_VULKAN OFF CACHE BOOL "" FORCE)
    set(AURA_ENABLE_OPENGL ON CACHE BOOL "" FORCE)
    set(AURA_ENABLE_CPU OFF CACHE BOOL "" FORCE)

    set(AURA_NATIVE_OPTIMIZE OFF CACHE BOOL "" FORCE)
    set(AURA_ENABLE_LTO OFF CACHE BOOL "" FORCE)
endif()

if(ANDROID)
    set(AURA_ENABLE_VULKAN ON CACHE BOOL "" FORCE)
    set(AURA_ENABLE_OPENGL OFF CACHE BOOL "" FORCE)
    set(AURA_ENABLE_CPU OFF CACHE BOOL "" FORCE)

    set(AURA_BUILD_SANDBOX OFF CACHE BOOL "" FORCE)
endif()