#ifndef AURA_HPP
#define AURA_HPP

#pragma once

#include <ink/ink_base.hpp>
#include <ink/Inkogger.h>
#include <ink/InkException.h>

#define APP_VERSION_MAJOR       0
#define APP_VERSION_MINOR       0
#define APP_VERSION_PATCH       1
#define APP_VERSION_STRING      INK_STR(APP_VERSION_MAJOR) "." INK_STR(APP_VERSION_MINOR) "." INK_STR(APP_VERSION_PATCH)
#define APPLICATION_VERSION     VK_MAKE_API_VERSION(APP_VERSION_MAJOR, APP_VERSION_MINOR, APP_VERSION_PATCH)

#define ENGINE_VERSION_MAJOR    APP_VERSION_MAJOR
#define ENGINE_VERSION_MINOR    APP_VERSION_MINOR
#define ENGINE_VERSION_PATCH    APP_VERSION_PATCH

#define ENGINE_VERSION_STRING   APP_VERSION_STRING
#define ENGINE_VERSION          APP_VK_VERSION
#define API_VERSION             VK_API_VERSION_1_3

#define APPLICATION_NAME        "Aura3D"
#define ENGINE_NAME             "Aura3D Engine"
#define API_VERSION             VK_API_VERSION_1_3

#endif // AURA_HPP
